version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: flask/demo
    container_name: flask-demo
    hostname: flask-dev-demo
    volumes:
       - ./app:/app
    # command: sleep 3600